### ISSUE TITLE
runInTerminal service

### ISSUE THREAD

**Issue by UziTech** [bus-stop/terminus#1]
`platformio-ide-terminal` had a service called `runInTerminal` that was removed in https://github.com/bus-stop/terminus/commit/b915d30bc47a9507ce0ddc9073f161aca1b6b209

Could we add something like that to this package to run commands from other packages.

I have a package ([`terminal-commands`](https://atom.io/packages/terminal-commands)) that uses this service so you can run commands in the terminal from the command palette or tool-bar buttons.

**Comment by the-j0k3r** [comment]
@UziTech I removed it because it says it said `Deprecated API for PlatformIO IDE 1.0` I didn't see much need to provide support because of that.

If it is indeed useful I can re-add it for a later release, do you know if you need the whole lot re-added and could you test locally please, I rather not add anything its not necessary for this.

Thanks.

**Comment by UziTech** [comment]
I created PR #2 to add the non-deprecated service back. `terminal-commands` only needs the `run` function to run commands but the other functions might be helpful to other packages.

**Comment by UziTech** [comment]
if you want `terminus` to be compatible with `platformio-ide-terminal` you might want to leave the services in with the same names. Just a simple search shows there are [about 200 packages](https://github.com/search?q=consumedServices+runInTerminal&type=Code) that use the `runInTerminal` service and [about 100](https://github.com/search?q=consumedServices+platformioIDETerminal&type=Code) use the `platformioIDETerminal` service

**Comment by the-j0k3r** [comment]
>if you want terminus to be compatible with platformio-ide-terminal

Ide prefer not to add deprecated stuff back and compatibility with `platformIO` anything is definitely not something in my mind.

FYI, Im trying to decaffeinate the project also, for which support from the community would be great.
See  https://github.com/bus-stop/terminus/commits/decaffeinated-terminus, the project works, but errors when changing settings.

Im still not proficient enough in JS to tackle those errors and make the conversion from Coffeescript to JS cleanly, but I managed to get the terminal to open, its a great stride and hopefully will be better to get the community involved with development, since without the communities help, we may as well not have forked.

Thanks again.

Thanks for PR and issue ticket.
