### ISSUE TITLE
Uncaught Error: Channel closed

### ISSUE THREAD

**Issue by basilsage** [bus-stop/terminus#175]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Unknown macOS version
**Thrown From**: [terminus](https://github.com/bus-stop/terminus) package 4.0.6

### Stack Trace

Uncaught Error: Channel closed

```
At events.js:177

Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at Task.send (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43629)
    at TerminusView.resize (/packages/terminus/lib/view.js:351:21)
    at TerminusView.resizeTerminalToView (/packages/terminus/lib/view.js:624:10)
    at TerminusView.focus (/packages/terminus/lib/view.js:580:10)
    at /packages/terminus/lib/status-bar.js:129:30
```

### Commands

```
     -2:19.7.0 application:reopen-project (div#add-projects-view.)
     -1:58.6.0 core:select-all (input.hidden-input)
     -1:58.2.0 core:backspace (input.hidden-input)
     -1:05.4.0 pane:show-item-1 (input.hidden-input)
     -1:04.9.0 pane:show-item-2 (input.hidden-input)
     -1:03.6.0 application:new-file (input.hidden-input)
  2x -1:02.7.0 core:save (input.hidden-input)
     -0:44.4.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-django 0.3.2 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autocomplete-python 1.16.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
terminus 4.0.6 
```

**Comment by the-j0k3r** [comment]
Bad install or upgrade, blame apm/node-gyp, =(

1. Close Atom (all instances)
1. Remove `~/.atom/packages/terminus`
1. run on an external terminal `apm install terminus`
1. Open Atom profit

Cant do anything to fix the issues are many and outside our control. Best solution on any failure is rinse and repeat steaps above, if persists make sure you purge old apm/npm caches for good measure.

It works otherwise in all OS's with sane Atom installs
