### ISSUE TITLE
[Q] 

### ISSUE THREAD

**Issue by sasharkv** [bus-stop/terminus#178]
### I would like to be able do the following

1.
2.
3.

**Comment by sasharkv** [comment]
I've updated the package yesterday and can't see the terminus  icon anymore. 

Any suggestions on how to fix it? 

Or how can I go t the previous version?

**Comment by the-j0k3r** [comment]
Bad install or upgrade, hard to tell since info provided is not the desired issue template, =(

1. Close Atom (all instances)
1. Remove `%userprofile%\.atom\packages\terminus`
1. run on an external terminal `apm install terminus`
1. Open Atom profit

Cant do anything to fix the issues are many and outside our control. Best solution on any failure is rinse and repeat steaps above, if persists make sure you purge old apm/npm caches for good measure.

It works otherwise in all OS's with sane Atom installs
