### ISSUE TITLE
[BR] Strange output

### ISSUE THREAD

**Issue by tjapro** [bus-stop/terminus#24]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [x] I have not tried uninstalling/reinstalling the terminal.
### Description

A strange output is showing in beggining of terminal.
```
bash: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
bash: erro ao importar definição de função para "switchml"
bash: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
bash: erro ao importar definição de função para "module"
bash: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
bash: erro ao importar definição de função para "scl"
/usr/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/usr/bin/sh: erro ao importar definição de função para "switchml"
/usr/bin/sh: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/usr/bin/sh: erro ao importar definição de função para "module"
/usr/bin/sh: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/usr/bin/sh: erro ao importar definição de função para "scl"
/usr/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/usr/bin/sh: erro ao importar definição de função para "switchml"

....
```

### Steps to reproduce

1. Open Atom
2. Open the terminal
3. The strange output appears

**Expected behavior:**

No strange output.

**Actual behavior:**

The strange output appears.

**Reproduces how often:**

Always.

### Versions

```
> atom --version
/bin/bash: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/bash: erro ao importar definição de função para "switchml"
/bin/bash: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/bash: erro ao importar definição de função para "module"
/bin/bash: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/bash: erro ao importar definição de função para "scl"
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> apm --version
/bin/bash: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/bash: erro ao importar definição de função para "switchml"
/bin/bash: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/bash: erro ao importar definição de função para "module"
/bin/bash: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/bash: erro ao importar definição de função para "scl"
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python switchml:
git 2.24.1
```
OS name and version: Fedora 31
Terminal version: latest

**Comment by the-j0k3r** [comment]
Hello @TJProgrammer thanks for this bug report.

Something comes to mind,  Your errors indicate something external to terminus is not configured properly system wide we dont use `switchml`

>switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado

This means `>switchml: line 1:syntax error unexpected end of folder`,  Ive never seen this error with folders but seen with files.

>erro ao importar definição de função para "switchml"

This means there was an error importing definitions for the `switchml` function.

Does your system have some customization that has created a `switchml` function that terminus is not reading properly? Maybe exporting path related issue. 

Causes can be some 3rd party something you added, a Atom addon or script or standalone program either pre installed or that you installed.

What happens when you open a regular terminal outside Atom?

If you dont experience this issue in regular terminal, try this..

1) Export any paths this `switchml` is exporting to your `~/.bash_profile`
2) uninstall any switchml anything ou have and purge config files
3) restart system for good measure.
4) Retry to dupe issue.

**Comment by TJProgrammer** [comment]
`dnf info switchml` doesn't show anything...

> Export any paths this switchml is exporting to your ~/.bash_profile and not just .bashrc

In .bashrc doesnt mention switchml, and in .bash_profile the .bashrc is sourced.

> Investigate any switchml issues. some ref here look at /etc/profile.d/modules.sh maybe.

Thanks, but in analysis ...

> restart system for good measure

Restarted and re-installed the package `terminus`and the same problem.

---
> /bin/bash: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
>/bin/bash: erro ao importar definição de função para "scl"

I've made some old research and I found this: 
https://github.com/atom/atom/issues/13451
https://github.com/atom/atom/pull/17508
Do you think this is related?

**Comment by the-j0k3r** [comment]
>dnf info switchml doesn't show anything...

switchml afaik is part of environment-modules [as shown here ](https://www.spinics.net/linux/fedora/fedora-users/msg494147.html)so the output of:

`rpm -q environment-modules`

or similar command should provide more info. The environment-modules could be a dependency of a program you installed.

>I've made some old research and I found this:
atom/atom#13451
atom/atom#17508
Do you think this is related?

Those could be related, but without further investigation as to root cause could shed some light into your specific issue, clearly there's similarities and many relies indicate things you can explore in your way to getting to the bottom of this.

I would see about https://github.com/atom/atom/issues/13451#issuecomment-267357959 and other replies as a way to investigate.

Sorry I couldn't be of more help at this time. I dont have time to setup a Fedora vm and then try to dupe your issue either, but I can suggest to you to do this in a clean OS install VM + atom + terminus and nothing else installed that the OS doesnt offer.

**Comment by TJProgrammer** [comment]
Confirmed a atom issue; see https://github.com/atom/atom/issues/20360.

**Comment by the-j0k3r** [comment]
@TJProgrammer so https://bugzilla.redhat.com/show_bug.cgi?id=1795425 indicates possible solutions have you tried it? If so whats the result?

**Comment by TJProgrammer** [comment]
@the-j0k3r, see https://github.com/atom/github/issues/2397#issuecomment-581571892

**Comment by the-j0k3r** [comment]
Yes, the bug report at redhat some comments offer possible solutions have you tried them?

**Comment by TJProgrammer** [comment]
Yes, I'm trying the solutions, but they are still inspecting the source of problem. But in my **specific case**, removing `scl-utils` solve (and that it's strange). Again, needs more inspecting ....
@ the-j0k3r you can always follow the issues that I cited above ...

**Comment by PerBothner** [comment]
I'm guessing this is this issue: https://github.com/atom/atom/issues/20389

**Comment by the-j0k3r** [comment]
Thanks, feel free to keep updating this report with relevant information. This would be also desirable especially if you find workarounds or fixes that could help others looking at this.

TIA =)

**Comment by TJProgrammer** [comment]
@the-j0k3r as you see there are already a PR!
